### ISSUE TITLE
使用几分钟以后就提示dial: no response

### ISSUE THREAD

**Issue by mackyzhan** [dearplain/fast-shadowsocks#1]
error connecting to shadowsocks server: dial: no response

此项目还更新吗？

**Comment by dearplain** [comment]
在哪种情况下出现的？一直出现no response吗？

**Comment by mackyzhan** [comment]
北京鹏博士内网宽带，使用几分钟以后就提示dial: no response，有可能是运营商发现UDP使用太多了就封锁UDP。KCP有更新，此项目更新一下呗。

**Comment by mackyzhan** [comment]
UDP没法测试了，单子先关了吧

**Comment by dearplain** [comment]
可以测试一下新版本。

**Comment by mackyzhan** [comment]
![image](https://cloud.githubusercontent.com/assets/10173218/20593288/bc4fc8a6-b26c-11e6-9e36-ca87f5b9c5ac.png)
host和guest能连上，但无法正常工作
