### ISSUE TITLE
能否增加TCP长连接、多路复用？

### ISSUE THREAD

**Issue by mackyzhan** [dearplain/fast-shadowsocks#2]
kcp使用的是UDP协议，我看kcptun项目作者讲，大量短连接不太适合KCP，有没有计划增加基于TCP连接的连接多路复用，可参考这个项目:
https://github.com/stormgbs/gopkg

**Comment by dearplain** [comment]
有计划多路复用，因为响应会更快一些，流量也好控制。
要保持tcp连接，一般30s内发心跳包就好了。
