### ISSUE TITLE
Frequent page hangs

### ISSUE THREAD

**Issue by WinstonPrivacy** [dearplain/fast-shadowsocks#3]
I'm experiencing many issues with hung connections when using the fast-shadowsocks library in a transparent proxy. This occurs on some page but not others. For instance, google.com works perfectly every time but the following URL consistently hangs before all resources have loaded:

https://itunes.apple.com/us/app/lightstreamer-stock-list-apns/id430328811?mt=8

Facebook and many other sites do the same. 

I'm using shadowsocks as a drop-in replacement for a TCP transport. My code looks something like this:
` transport := &http.Transport{
			Dial: func(network, addr string) (net.Conn, error) {
				rawAddr, err := ss.RawAddr(addr)
				if (err != nil) {
					return nil, err
				}
				conn, err := DialWithRawAddrKCP(rawAddr, serverAddr, cipher.Copy())
				if (err != nil) {
					return nil, err
				}
				return conn, err
}}
`

I've discovered that killing the local process will instantly cause the browser to crash with an error, so I suspect that the connection is not being close for some reason.

Any thoughts or assistance is apprecated!

**Comment by WinstonPrivacy** [comment]
I have been able to narrow this down to a somewhat consistently reproducible test case. The following URL will hang about once every 40 tries during mid-load. In Chrome, the first 563 bytes appear in the network tab (in developer tools) and the image will pause indefinitely. If the processing running the shadowsocks client transport is killed, the browser connection will then abort and 32.6k of the image is consistently loaded.

So it is almost certainly the case that network transmission problems are the cause. This occurs not only on images, but other file types as well and the seemingly random occurrence causes pages to arbitrarily hang or stop loading.

https://pbs.twimg.com/card_img/981358602219917313/3VhDili2?format=jpg&name=600x314

**Comment by dearplain** [comment]
In this project, I've made a mistake, I open one port on each connection, result in too much ports, which is forbidden by router? I don't know,  but I'm planning rewrite this logic and do more test, need more time.

**Comment by WinstonPrivacy** [comment]
Thanks for your quick reply! That part seems to be working well for me actually. I'm wrapping the pipe up in a transport and connection pooling ensures that it's limited to a reasonable number of ports.

However, I have been able to narrow the problem down to skcp.go/readLoop(). The data simply stops arriving and the session hangs there forever. You can reproduce this by opening up a pipe to a destination site and then closing the server down while repeatedly fetching the URL. The pipe never seems to figure out that the server has gone down.

**Comment by WinstonPrivacy** [comment]
Could it have something to do with timeouts? I noticed that there are many times when readloop stops getting data, it recovers in a few seconds and gets the rest of the file. However, on the failed attempts, readloop sits for awhile and then the server times out. Then it sits there forever.

**Comment by dearplain** [comment]
A pipe is like a tcp connection, if server shutdown unexpectedly, that pipe is not longer usable, you have to create new one and connect to server.

**Comment by WinstonPrivacy** [comment]
The problem is that the ACKS are sometimes dropping. If you update ikcp.go to the latest version (found elsewhere), it fixes it completely. Works even faster than before!

**Comment by dearplain** [comment]
That's good, ikcp.go is converted from skywind3000/kcp project using c to go convert tool, I will update it.

**Comment by dobegor** [comment]
@dearplain may I ask why did you use conversion from c to go (and which particular tool?) instead of using native Go implementation? https://github.com/xtaci/kcp-go

**Comment by dearplain** [comment]
https://github.com/rsc/c2go ? I don't remember now.
I created this before xtaci/kcp-go was borned.

**Comment by dearplain** [comment]
I have synced ikcp.go with https://github.com/vzex/dog-tunnel/blob/master/ikcp/ikcp.go.

**Comment by dearplain** [comment]
Underlying code has changed, so this issue is out of date.
