### ISSUE TITLE
Any improvement by trying out utp? 

### ISSUE THREAD

**Issue by wangyoucao577** [dearplain/fast-shadowsocks#5]
By the way, [anacrolix/utp](https://github.com/anacrolix/utp) has been deprecated in favour of [anacrolix/go-libutp](https://github.com/anacrolix/go-libutp), see https://github.com/anacrolix/utp/issues/26

**Comment by dearplain** [comment]
都测试过了，anacrolix/utp在晚高峰的时候很慢，anacrolix/go-libutp更加不行。
我已经重新写了一个自己的udp协议，很简洁，比kcptun表现更好，已经自用几个月了，有空的话会放代码出来。

**Comment by wangyoucao577** [comment]
@dearplain 差点手抖更新。。更新utp之前的版本还是蛮不错的，建议发个release的版本出来作为稳定版本，后续升级也可以不被影响。需要的话我可以提供PR，包含基于Github Actions的自动binary编译、打包、上传到release页面等等，使用者也就不需要自己`go get`编译代码了。   
多问一句，有试过QUIC或者UDT、SRT之类的协议么？之前也研究过这块协议，主要用于优化弱网环境下的视频直播。TCP的设计追求公平性，拥塞控制比较保守，不过自己基于UDP设计的协议调优起来也不容易啊。

**Comment by dearplain** [comment]
之前版本不太行，我没用了。代码也丑，不想改了。Github Actions到时候加下。
QUIC或者UDT、SRT需要测试下，个人觉得不会比KCPTUN好。

**Comment by wangyoucao577** [comment]
之前的版本比默认基于tcp的版本还是明显要好的。后面还是基于这个代码接着升级么？是的话，要么把utp的改动revert一下，我可以来提个PR加github actions，没意见的话最好也支持下`go mod`。不基于这个代码的话就算了。

**Comment by dearplain** [comment]
更新了版本，建议使用这个或者kcptun，旧的不再维护。

**Comment by wangyoucao577** [comment]
实测数据非常不错，大写的赞👍
